apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: unleash
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://docs.getunleash.io/helm-charts'
    targetRevision: 3.0.2
    chart: unleash
    helm:
      values: |-
        service:
          type: NodePort
          port: 34242
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: infra
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
    automated:
      prune: true
