apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: unleash
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://docs.getunleash.io/helm-charts'
    targetRevision: 3.0.2
    chart: unleash
    helm:
      values:
        valuesObject:
          livenessProbe:
            path: /unleash/health
          readinessProbe:
            path: /unleash/health
          env:
            - name: INIT_CLIENT_API_TOKENS
              value:  default:development.unleash-insecure-api-token
            - name: BASE_URI_PATH
              value: /unleash
            - name: LOG_LEVEL
              value: debug
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: infra
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
    automated:
      prune: true
